---
- name: installing dependencies
  apt: "pkg={{item}} state=latest force=yes"
  with_items:
    - fontconfig

- name: downloading package {{version}}
  get_url:
    url: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-{{version}}-linux-x86_64.tar.bz2
    dest: /usr/local/share/phantomjs-{{version}}-linux-x86_64.tar.bz2
    force: no

- name: unarchiving the package
  unarchive: >
    src=/usr/local/share/phantomjs-{{version}}-linux-x86_64.tar.bz2
    dest=/usr/local/share/
    creates=/usr/local/share/phantomjs-{{version}}-linux-x86_64
    copy=no

- file: src=/usr/local/share/phantomjs-{{version}}-linux-x86_64/bin/phantomjs dest={{item}} state=link
  with_items:
    - /usr/local/share/phantomjs
    - /usr/local/bin/phantomjs
    - /usr/bin/phantomjs
